---

- name: restart neo battery shutdown service
  systemd:
    name: "{{ hat_service_name }}"
    daemon_reload: yes
    state: restarted

- name: remove build and files
  file:
    path: /home/*
    state: absent


- name: get rigd of gcc
  apt:
    name: gcc
    state: absent
