---

# For RPi Raspbian versions (they have internal wifi)
# Use selected client_facing_if specified wlan in two files

- name: queue up wlan changes
  debug:
    msg: Queing up wlan changes.
  changed_when: True
  notify:
    - update ConnectBoxManage.sh
    - update cli.py
  when: connectbox_os == "raspbian"


