---
nginx_available_vhosts_path: /etc/nginx/sites-available
nginx_enabled_vhosts_path: /etc/nginx/sites-enabled

# Interface type (valid options)
# - icon_only (default)
# - static_site
# If this is useful in other roles, we can define it at a higher level
interface_type: icon_only
nginx_vhost_file_moodle: connectbox_moodle.conf
nginx_vhost_file_icon_only: connectbox_icon-only.conf
nginx_vhost_file_static_site: connectbox_static-site.conf
nginx_vhost_file_captive_portal: connectbox_captive-portal.conf

# Mapping interface type to the actual vhost file used by nginx
interface_type_files:
  icon_only: "{{ nginx_vhost_file_icon_only }}"
  static_site: "{{ nginx_vhost_file_static_site }}"
