language: python
python:
  - "3.6"
dist: trusty
cache:
  directories:
  - "$HOME/.cache/pip"
  pip: true
  timeout: 86400
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
install:
- export PATH=$PATH:$PWD
- pip install -r requirements.txt
script:
- $TRAVIS_BUILD_DIR/ci/script_run_on_pull_requests.sh;
- pushd $TRAVIS_BUILD_DIR && ansible-lint -x ANSIBLE0004,ANSIBLE0006,ANSIBLE0010,ANSIBLE0012
  --exclude=ansible/roles/mikegleasonjr.firewall --exclude=ansible/roles/geerlingguy.nginx
  ansible/site.yml && popd
notifications:
  slack:
    rooms:
      - secure: jGRq7hp2sSz7xXSfMwNMKOgTgR5nO+He39jfiyLA6MjUchcqVyvxj6F1X7lIemyee9sud650sWjO7sWnWHkq024jQkONnlxUzrIQMAt4DuhN+BNmDO7+hHnmLHfQSkevtUEBVYFSP8KV16sXyS11aUHhjrZn+JW3Ozpb1nYummcAKVZ0OfWhHuwoLIK3qtgWDoiWA796JEUDIySR25JsnRRZIW09L0lg/528SD9scH/52DqpMCoLuRtsYBY4v2BMndillnsvo4P6dMfvKFhLCmNuabgyIPxOZ6vE1YD4uHCh67fXOwsjMk3+Kv6huPp3K5CVj3/84V6VDlLTvrlzuNiS7SKD4Y1mb7nDCGTv5ybIjDRPe90NEg3rClbPD9zH6fPTl7/MTkDDB+sRaTGXoQ/g+stc0W6/m8FIU6oZSfgm1XKp1FhOrv43oWUtM1A5G9xo3gYMl1aSCmolDqV+dqAEaTgr5PgTrYWgK1mNv7l8zTAsSpi5BgH3tHEN8UGFkJXmRukLr6hNoSt+QlTI9BxFBDIuy8nkE5DoGlxTKj0JXXH2vSahd/fkc+pXOBrKD3e6DRZuelaeKK9RzpAGu7OaeUJCUH4tWzBAjzqFlgksczVsT7pygASH0nLU2s3XT3FJmUSmpT8mzD+mVsjD8NFFGSMou91YqHdypfy84SU=
    on_success: change
    on_pull_requests: false
