---
- name: Reload udev rules
  command: udevadm control --reload-rules

- name: Reload systemd-udevd unit file and restart service
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-udevd

# We can't actually remount the USB without walking all the devices
#  so let's just print a message (that will likely get missed)
- name: Warn to remount USB
  debug:
    msg: Remove and reinsert your USB storage. Mount options have changed.
