---
language: python
python: "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i localhost, tests.yml --syntax-check
  - ansible-playbook -i localhost, tests.yml --connection=local --sudo
  - >
    ansible-playbook -i localhost, tests.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/