---

- name: Create drop-in directory for systemd-udevd
  file:
    path: /etc/systemd/system/systemd-udevd.service.d
    state: directory

- name: Teach systemd-udev to expose mount points to the system
  copy:
    dest: /etc/systemd/system/systemd-udevd.service.d/mountflags.conf
    content: |
      [Service]
      MountFlags=shared
  notify:
    - Reload systemd-udevd unit file and restart service

- name: reload systemd-udevd unit
  command: udevadm trigger --action=change
  ignore_errors: yes
  
