---
#  Task to remove all *.lz4 files in /var/lib/apt/lists

#  Find all lz4 files, 
#  store the list files_to_delete
  - name: create the lz4 delete file glob
    find:
      paths: /var/lib/apt/lists
      patterns: "*.lz4"
    register: files_to_delete

# ... and use that list to loop through the delete
  - name: remove the file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    no_log: True
