---
- name: Make captive portal virtualenv base directory
  file:
    path: "{{ captiveportal_virtualenv_dir }}"
    state: directory

        
- name: Make log file location under connectbox log directory for captive-portal
  file:
    path: "{{connectbox_log_dir}}/captive_portal-access.log"
    state: touch

- name: Make log file location under connectbox log directory for connectbox
  file:
    path: "{{connectbox_log_dir}}/connectbox-error.log"
    state: touch

- name: install the right version of Werkzeug tools
  pip:
    virtualenv: "{{ captiveportal_virtualenv_dir }}"
    virtualenv_python: python3
    name: Werkzeug==1.0.0

- name: Setup captive portal virtualenv
  pip:
    virtualenv: "{{ captiveportal_virtualenv_dir }}"
    virtualenv_python: python3
    name: git+https://github.com/ConnectBox/simple-offline-captive-portal.git
  notify:
    - Restart captiveportal

- name: Copy captive portal tempfiles definition
  template:
    src: etc_tmpfiles.d_captiveportal.conf.j2
    dest: /etc/tmpfiles.d/captiveportal.conf

- name: Copy captiveportal systemd unit file
  template:
    src: etc_systemd_system_captiveportal.service.j2
    dest: /etc/systemd/system/captiveportal.service
  notify: Restart captiveportal

- name: Enable captiveportal service
  service:
    name: captiveportal
    enabled: yes
    #state: started
