---
- name: Make captive portal virtualenv base directory
  file:
    path: "{{ captiveportal_virtualenv_dir }}"
    state: directory

- name: Create the Connectbox directory
  file:
    path: "/var/log/connectbox"
    state: directory
        
- name: Make log file location
  file:
    path: "/var/log/connectbox/captive_portal-access.log"
    state: touch
<<<<<<< HEAD
=======
    mode: "u=rw, o=rw"
>>>>>>> 622b0ca901e93b9d1798ce2a651b2c4c7108ea4f

- name: Setup captive portal virtualenv
  pip:
    virtualenv: "{{ captiveportal_virtualenv_dir }}"
    virtualenv_python: python3
    name: git+https://github.com/ConnectBox/simple-offline-captive-portal.git
  notify:
    - Restart captiveportal

- name: Copy captive portal tempfiles definition
  template:
    src: etc_tmpfiles.d_captiveportal.conf.j2
    dest: /etc/tmpfiles.d/captiveportal.conf

- name: Copy captiveportal systemd unit file
  template:
    src: etc_systemd_system_captiveportal.service.j2
    dest: /etc/systemd/system/captiveportal.service
  notify: Restart captiveportal

- name: Enable captiveportal service
  service:
    name: captiveportal
    enabled: yes
    #state: started
