#!/usr/bin/perl

# A proxy to give easy command line access to connectbox-manage cli

my ($command,$key,$value) = @ARGV;
system("cd /var/www/enhanced/connectbox-manage/src && ./clientcli.py $command $key $value");
