---
- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "/var/www/enhanced"
    - "/var/www/enhanced/content"
    - "/var/www/enhanced/admin"
    - "/var/www/enhanced/connectbox-manage"

- name: Install zip 
  apt:
    name: zip
    state: present

- name: Install unzip 
  apt:
    name: unzip
    state: present

- name: Install wget 
  apt:
    name: wget
    state: present

# Install ffmpeg to handle mpeg 
- name: Install ffmpeg to handle thumbnails for interface
  apt:
    pkg:
    - ffmpeg

- name: Get media interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/mediainterface/releases/download/latest/latest.zip
    dest: /var/www/enhanced/content/
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0775

- name: Get admin interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/cbadmin/releases/download/latest/latest.zip
    dest: /var/www/enhanced/admin/
    remote_src: yes
    owner: www-data
    group: www-data

- name: Download script to add node to apt cache
  get_url:
    url: https://deb.nodesource.com/setup_14.x
    dest: /tmp/setup_14.sh
    mode: '0755'
  when: connectbox_os != "armbian"

- name: Add node to apt cache
  command: "/tmp/setup_14.sh"
  become: true
  when: connectbox_os != 'armbian'

- name: Install nodejs for connectbox-manage
  apt:
    name: nodejs
    state: present
  when: connectbox_os != 'armbian'

- name: Get the setup_16 for non-raspbian
#  command: curl -sL https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_16.x | sudo -E bash
  command: curl -fsSL https://deb/nodesource.com/setup_16.x | bash -
  when: connectbox_os == "armbian"
  ignore_errors: yes

- name: install nodejs for non-raspbian
  command: sudo apt-get install -y nodejs
  when: connectbox_os == "armbian"

- name: show the node version that we instailled
  command: node --version
  register: node_ver

- name: print the node version
  debug:
    msg: "We loaded node version {{ node_ver.stdout }}"

- name: Install pm2 -- node process manager for connectbox-manage
  community.general.npm:
    name: pm2
    global: yes
    state: present
  become: true  

- name: get the pm2 version we loaded
  command: pm2 --version
  register: pm2_ver

- name: display the version of pm2 we loaded
  debug:
    msg: "we loaded version {{ pm2_ver.stdout }} of PM2"

- name: Get connectbox-manage repo from https://github.com/RT-coding-team/connectbox-manage.git
  git:
    repo: https://github.com/RT-coding-team/connectbox-manage.git
    dest: /var/www/enhanced/connectbox-manage
    clone: yes
    update: yes

- name: Run npm to install dependencies for connectbox-manage
  community.general.npm:
    path: /var/www/enhanced/connectbox-manage
    
- name: Delete existing pm2 processes
  command: "pm2 delete all"
  ignore_errors: yes

- name: Pause for pm2
  pause:
    seconds: 2

- name: Start pm2 for connectbox-manage
  command: "pm2 start /var/www/enhanced/connectbox-manage/src/index.js"
  become: true

- name: Pause for pm2
  pause:
    seconds: 2

- name: Get pm2 status and check for process online
  shell:
    cmd: "pm2 status |grep index |grep online"
  become: true
  register: pm2status
  failed_when: pm2status.stdout == ""

- name: Save pm2 config
  shell:
    cmd: "pm2 save"
  become: true

- name: Run pm2 startup to retain pm2 config on reboot
  shell:
    cmd: "pm2 startup"
  become: true

- name: Cause phonehome.py to execute every 10 minutes via cron IF not a Moodle box  (We have different process for Moodle)
  ansible.builtin.cron:
    name: "phonehome.py"
    minute: "*/10"
    user: www-data
    job: "/usr/bin/python /usr/local/connectbox/bin/phonehome.py >/tmp/push_messages.log  2>&1"

- name: Update enhanced template footer for Moodle if build_moodle
  replace:
    path: /var/www/enhanced/content/www/assets/templates/footer.html
    regexp: 'ifMoodle hidden'
    replace: 'ifMoodle'
  when: build_moodle

- name: Update enhanced template footer for Moodle if build_moodle
  replace:
    path: /var/www/enhanced/content/www/assets/templates/footer.html
    regexp: 'DOMAIN'
    replace: '{{ connectbox_default_hostname }}'
  when: build_moodle

- name: Copy footer from template to content for live
  ansible.builtin.copy:
    src: /var/www/enhanced/content/www/assets/templates/footer.html
    dest: /var/www/enhanced/content/www/assets/content/footer.html
    remote_src: yes
  when: build_moodle

- name: Update hostname in MMI
  replace:
    path: /var/www/enhanced/content/www/assets/content/en/data/interface.json
    regexp: 'hostname'
    replace: '{{ connectbox_default_hostname }}'

- name: Copy MMI loader to /usr/local/connectbox/bin
  get_url:
    url: https://raw.githubusercontent.com/RT-coding-team/mediainterface/main/mmiloader.py
    dest: /usr/local/connectbox/bin/enhancedInterfaceUSBLoader.py
    owner: _connectbox
    group: _connectbox
    mode: '0755'

- name: Copy MMI loader to /usr/local/connectbox/bin
  get_url:
    url: https://raw.githubusercontent.com/RT-coding-team/mediainterface/main/lazyLoader.py
    dest: /usr/local/connectbox/bin/lazyLoader.py
    owner: _connectbox
    group: _connectbox
    mode: '0755'

- name: Create file to access connectboxmanage as command line
  become: true
  copy:
    src: bin_connectboxmanage
    dest: /bin/connectboxmanage
    mode: '0755'

- name: Make log file location under connectbox log directory for enhanced content stats
  file:
    path: "{{connectbox_log_dir}}/connectbox_enhanced.log"
    state: touch
