---
- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "/var/www/enhanced"
    - "/var/www/enhanced/content"
    - "/var/www/enhanced/admin"

- name: Install unzip 
  apt:
    name: unzip
    state: present

- name: Install wget 
  apt:
    name: wget
    state: present

- name: Get media interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/mediainterface/releases/download/latest/latest.zip
    dest: /var/www/enhanced/content/
    remote_src: yes
    owner: www-data
    group: www-data

- name: Get admin interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/cbadmin/releases/download/latest/latest.zip
    dest: /var/www/enhanced/admin/
    remote_src: yes
    owner: www-data
    group: www-data

- name: Cause phonehome.py to execute every 10 minutes via cron IF not a Moodle box  (We have different process for Moodle)
  ansible.builtin.cron:
    name: "phonehome.py"
    minute: "*/10"
    user: www-data
    job: "/usr/bin/python /usr/local/connectbox/bin/phonehome.py >/tmp/push_messages.log  2>&1"
