---
- name: create folders for default content/shared and config
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "/var/www/enhanced"
    - "/var/www/enhanced/content"
    - "/var/www/enhanced/admin"

- name: Install unzip 
  apt:
    name: unzip
    state: present

- name: Get media interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/mediainterface/releases/download/latest/latest.zip
    dest: /var/www/enhanced/content/
    remote_src: yes
    owner: www-data
    group: www-data

- name: Get admin interface latest release
  ansible.builtin.unarchive:
    src: https://github.com/RT-coding-team/cbadmin/releases/download/latest/latest.zip
    dest: /var/www/enhanced/admin/
    remote_src: yes
    owner: www-data
    group: www-data

