---

# Some build environments (ex: RPi4) do not remove lz4 files 
#  from /var/lib/apt/lists. These are not necessary and take 
#  up unnecessary space in the build

  - name: set up lz4 handler
    debug:
      msg: Queing up lz4 removal task
    notify:
      - create the lz4 delete file glob
      - remove the file glob
    changed_when: True

