# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.ssh.username = "admin"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-9d6c128a"
    aws.region = "us-east-1"
    aws.instance_type = "t2.nano"
    aws.keypair_name = "travis-ci-biblebox"
    override.ssh.username = "admin"
    override.ssh.private_key_path = "travis-ci-biblebox.pem"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/site.yml"
  end
end
