---

postgresql_backup_local_dir: ~postgres/backup
postgresql_backup_active_dir: "{{ postgresql_backup_local_dir }}/active"
postgresql_backup_mail_recipient: postgres
postgresql_backup_rotate: true
postgresql_user_name: postgres
postgresql_user_password: mypassword

postgresql_archive_wal_rsync_args: '--ignore-existing -ptg --info=skip1'
