---
ssid: "{{connectbox_default_hostname}} - Free Media"
wireless_channel: 1
# Only used as an override. Country code is automatically set when the
#  wifi device comes up, and defaults to the world regulatory domain 00.
#  To override, set an entry based on those in the following file:
# https://git.kernel.org/cgit/linux/kernel/git/sforshee/wireless-regdb.git/tree/db.txt
wireless_country_code: ""
