# For testing of ansible playbook commands
# Fill in the commands below "tasks" 
# Run with:
#  ansible-playbook -i inventory -b -e connectbox_os=raspbian Ansible_Testing.yml


- hosts: all

  tasks:

  - name: Check for device_type CM4
    replace:
      path: /usr/local/connectbox/brand.txt
      regexp: '"Device_type": *,'
      replace: '"Device_type": "CM",'



  - name: Check if multiple-batteries are available
    replace:
      path: /usr/local/connectbox/brand.txt
      regexp: '"Screen_Enable": [
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
        ],'
      replace: '"Screen_Enable": [
        {{ lcd_pages_main }},
        {{ lcd_pages_info }},
        {{ lcd_pages_battery }},
        0,
        {{ lcd_pages_memory }},
        {{ lcd_pages_stats_hour_one }},
        {{ lcd_pages_stats_hour_two }},
        {{ lcd_pages_stats_day_one }},
        {{ lcd_pages_stats_day_two }},
        {{ lcd_pages_stats_week_one }},
        {{ lcd_pages_stats_week_two }},
        {{ lcd_pages_stats_month_one }},
        {{ lcd_pages_stats_month_two }},
        {{ lcd_pages_admin }}
        ],'
  
  - name: Check for device_type CM4
    replace:
      path: /usr/local/connectbox/brand.txt
      regexp: '"Device_type": *,'
      replace: '"Device_type": "CM",'


