# For testing of ansible playbook commands
# Fill in the commands below "tasks" 
# Run with:
#  ansible-playbook -i inventory -b -e connectbox_os=raspbian Ansible_Testing.yml


- hosts: all

  tasks:

  - name: Check for CM4 modules
    lineinfile:
      dest: /proc/cpuinfo
      line: "Compute Module" 
    check_mode: yes
    register: CM4_present
  

  - name: Check for device_type CM4
    replace:
      path: /usr/local/connectbox/brand.txt
      regexp: '"Device_type": .*,'
      replace: '"Device_type": "CM2",'
    when: CM4_present


  - name: Check if multiple-batteries are available
    replace:
      path: /usr/local/connectbox/brand.txt
#      regexp: '"Screen_Enable": \[.*$(^.*,?.*$)^.*\]'
      regexp: '"Screen_Enable": \[(.*\n?)*.*\]'
      replace: '"Screen_Enable": \[
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0
        \]'
    when: CM4_present  
